name: tests unitaires
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]
    steps:
      - name : Set up Python for Demo
        uses : actions/setup−python@v4
        with :
          python−version : ${{ matrix.python−version }}
      - name: install pytest
        run: pip3 install pytest
      - uses: actions/checkout@v3
      - name: Set up Python for Demo
        uses: actions/setup-python@v4
      - name: Run tests
        run: pytest TP1/test.py
      - name: Branche 
        run: echo "Nom branche :" ${{ github.ref }}
      - name: OS
        run: echo "Nom repo :" ${{ runner.os }}.
        
